name: "build pipeline for web release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web

      # copy file for netlify.toml
      - name: Copy build settings to build folder
        run: cp netlify.toml build/web/

      # deploy application to netlify
      - name: Deploy production to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './build/web'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"